name: Create Subfolder Release

on:
  push:
    tags:
      - 'release-*'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get tag and release name
      id: get_tag
      run: |
        echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        echo "RELEASE_NAME=${GITHUB_REF#refs/tags/release-}" >> $GITHUB_ENV

    - name: Validate tag pattern
      id: validate_tag
      run: |
        if [[ "$TAG_NAME" =~ ^release-.+ ]]; then
          echo "valid=true" >> $GITHUB_OUTPUT
        else
          echo "valid=false" >> $GITHUB_OUTPUT
        fi

    - name: Exit if tag is invalid
      if: steps.validate_tag.outputs.valid != 'true'
      run: exit 0

    - name: Find matching folder
      id: find_folder
      run: |
        MATCH=$(find Assets -type d -regex 'Assets/com\.edia\.[^/]*' | head -n 1)
        if [ -z "$MATCH" ]; then
          echo "No matching folder found"
          exit 1
        fi
        echo "MATCHED_FOLDER=$MATCH" >> $GITHUB_ENV
        echo "Matched folder: $MATCH"

    - name: Create release asset archive
      run: |
        FOLDER_NAME=$(basename "$MATCHED_FOLDER")
        mkdir release
        cp -r "$MATCHED_FOLDER" "release/"
        cd release
        zip -r "../release-${RELEASE_NAME}.zip" "$FOLDER_NAME"
        cd ..

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.TAG_NAME }}
        name: Release ${{ env.RELEASE_NAME }}
        files: release-${{ env.RELEASE_NAME }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
